FROM alpine:3.19.1 AS builder
WORKDIR /app
COPY ./dev/full-cycle.go .
# COPY ./go1.22.0.linux-amd64.tar.gz /usr/local
RUN wget https://go.dev/dl/go1.22.0.linux-amd64.tar.gz -P /usr/local
RUN tar -C /usr/local -xzf /usr/local/go1.22.0.linux-amd64.tar.gz
RUN rm /usr/local/go1.22.0.linux-amd64.tar.gz
ENV PATH="${PATH}:/usr/local/go/bin"
RUN go build full-cycle.go

FROM scratch
WORKDIR /app
COPY --from=builder /app/full-cycle /app
CMD [ "./full-cycle"]